services:
  db:
    image: postgres:alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: chess
    volumes:
      - ./db_data:/var/lib/postgresql/data
  app:
    image: node:alpine
    ports:
      - 80:3000
    command: sh -c "cd /app && yarn install && yarn migrate:latest && yarn start:dev"
    volumes:
      - ./app:/app
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/chess
